"""
Phase 2 — Build warm start dataset
====================================
Generates and oracle-labels the warm start used to seed the AL simulation.

Composition mirrors the market_supplement_ratio assumption from simulation.yaml:
  - (1 − market_supplement_ratio) × weekly_budget real portfolio rows
  - market_supplement_ratio × weekly_budget rows from the supplement pool

The supplement pool is generated by create_market_supplement() using the
configured market_profile_method (cp or gaussian) from market_n_anchors
anchor rows — the same mechanism used by the random_market strategy each week.
This ensures the warm start reflects the same market composition assumption as
the ongoing AL loop.

Outputs
-------
  outputs/warm_start/warm_start_X.parquet  — engineered feature profiles
  outputs/warm_start/warm_start_y.npy      — oracle-predicted premiums (aligned)
  outputs/warm_start/metadata.json         — mix config for reproducibility

Run this script once before running 05_al_simulation.py.
"""

import json
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

from market_model_al.features import load_raw, engineer_features
from market_model_al.oracle_engine import OraclePricingEngine
from market_model_al.profile_generator import create_market_supplement
from market_model_al.config import load_simulation_cfg

# ── Load config from simulation.yaml ─────────────────────────────────────────

sim_cfg = load_simulation_cfg(ROOT / "config" / "simulation.yaml")

SEED                    = sim_cfg["seed"]
WEEKLY_BUDGET           = sim_cfg["weekly_budget"]
WARMUP_WEEKS            = sim_cfg["warmup_weeks"]
MARKET_SUPPLEMENT_RATIO = sim_cfg["market_supplement_ratio"]
MARKET_N_ANCHORS        = sim_cfg["market_n_anchors"]
MARKET_PROFILE_METHOD   = sim_cfg["market_profile_method"]
GAUSSIAN_SIGMA          = sim_cfg["gaussian_sigma_frac"]
WARMUP_SCALE            = sim_cfg["warmup_scale"]

WARMUP_SIZE  = WEEKLY_BUDGET * WARMUP_WEEKS
N_SUPPLEMENT = max(0, int(WARMUP_SIZE * MARKET_SUPPLEMENT_RATIO))
N_REAL       = WARMUP_SIZE - N_SUPPLEMENT

# Oversampling counts: draw more than needed to absorb validation dropout,
# then trim to exact targets.
N_REAL_DRAW      = math.ceil(N_REAL * WARMUP_SCALE)
N_ANCHOR_SCALE   = math.ceil(WARMUP_SCALE)   # e.g. ceil(1.2) = 2

print("Warm start config (from simulation.yaml):")
print(f"  weekly_budget={WEEKLY_BUDGET}  warmup_weeks={WARMUP_WEEKS}"
      f"  → warmup_size={WARMUP_SIZE:,}")
print(f"  market_supplement_ratio={MARKET_SUPPLEMENT_RATIO}"
      f"  method={MARKET_PROFILE_METHOD}  warmup_scale={WARMUP_SCALE}")
print(f"  → target: {N_REAL:,} real rows + {N_SUPPLEMENT:,} supplement rows"
      f"  (market_n_anchors={MARKET_N_ANCHORS} × {N_ANCHOR_SCALE} = {MARKET_N_ANCHORS * N_ANCHOR_SCALE})\n")

# ── Paths ──────────────────────────────────────────────────────────────────────

WARM_DIR = ROOT / "outputs" / "warm_start"
WARM_DIR.mkdir(parents=True, exist_ok=True)

# ── Load data & oracle ─────────────────────────────────────────────────────────

print("Loading data and oracle…")
raw    = load_raw(ROOT / "data" / "raw" / "Motor vehicle insurance data.csv")
df     = engineer_features(raw)
TARGET = "Premium"
FEATURES = [c for c in df.columns if c != TARGET]

engine = OraclePricingEngine(ROOT / "outputs" / "models" / "oracle.pkl")
print(f"  Dataset: {len(df):,} rows × {len(FEATURES)} features")
print("  Oracle loaded.\n")

rng = np.random.default_rng(SEED)

# ── Component A: real rows ─────────────────────────────────────────────────────

print(f"(A) Sampling {N_REAL_DRAW:,} real portfolio rows (target {N_REAL:,} + oversampling)…")
real_sample = df[FEATURES].sample(n=N_REAL_DRAW, random_state=SEED)

valid_mask = engine.validate(real_sample)
n_invalid  = (~valid_mask).sum()
real_sample = real_sample[valid_mask].iloc[:N_REAL].reset_index(drop=True)
print(f"    {n_invalid} rows dropped (data-quality violations) → {len(real_sample):,} kept")

real_y = engine.query(real_sample)
print(f"    Oracle labels: mean={real_y.mean():.2f}  range=[{real_y.min():.2f}, {real_y.max():.2f}]\n")

# ── Component B: supplement profiles ─────────────────────────────────────────

if N_SUPPLEMENT > 0:
    n_anchors_draw = MARKET_N_ANCHORS * N_ANCHOR_SCALE
    print(f"(B) Building {MARKET_PROFILE_METHOD} supplement from {n_anchors_draw} anchors"
          f" (target {N_SUPPLEMENT:,} rows)…")
    anchors    = df[FEATURES].sample(n=n_anchors_draw, random_state=SEED + 1)
    supplement = create_market_supplement(
        anchors,
        n=N_SUPPLEMENT,
        method=MARKET_PROFILE_METHOD,
        rng=rng,
        gaussian_sigma_frac=GAUSSIAN_SIGMA,
    )
    print(f"    Supplement size: {len(supplement):,} profiles")
    supplement_y = engine.query(supplement)
    print(f"    Oracle labels: mean={supplement_y.mean():.2f}"
          f"  range=[{supplement_y.min():.2f}, {supplement_y.max():.2f}]\n")
else:
    print("(B) market_supplement_ratio = 0 — skipping supplement (real rows only)\n")
    supplement   = pd.DataFrame(columns=real_sample.columns)
    supplement_y = np.array([], dtype=float)

# ── Combine ────────────────────────────────────────────────────────────────────

warm_start_X = pd.concat([real_sample, supplement], ignore_index=True)
warm_start_y = np.concatenate([real_y, supplement_y])

# pd.concat with mismatched CategoricalDtype levels (real rows vs CP profiles)
# silently downcasts category columns to object.  Re-cast explicitly so the
# warm start has correct dtypes — otherwise CompetitorModel._prepare() pays an
# expensive astype("category") on the full labeled set at every fit/predict call.
for col in real_sample.select_dtypes("category").columns:
    warm_start_X[col] = warm_start_X[col].astype("category")

print(f"Warm start combined: {len(warm_start_X):,} profiles")
print(f"  Real rows  : {len(real_sample):,}  ({100*len(real_sample)/len(warm_start_X):.1f} %)")
print(f"  Supplement : {len(supplement):,}  ({100*len(supplement)/len(warm_start_X):.1f} %)"
      f"  [{MARKET_PROFILE_METHOD}]\n")

# ── Save ───────────────────────────────────────────────────────────────────────

X_path    = WARM_DIR / "warm_start_X.parquet"
y_path    = WARM_DIR / "warm_start_y.npy"
meta_path = WARM_DIR / "metadata.json"

warm_start_X.to_parquet(X_path, index=False)
np.save(y_path, warm_start_y)

metadata = {
    "weekly_budget"           : WEEKLY_BUDGET,
    "warmup_weeks"            : WARMUP_WEEKS,
    "warmup_size"             : WARMUP_SIZE,
    "market_supplement_ratio" : MARKET_SUPPLEMENT_RATIO,
    "market_profile_method"   : MARKET_PROFILE_METHOD,
    "market_n_anchors"        : MARKET_N_ANCHORS,
    "warmup_scale"            : WARMUP_SCALE,
    "seed"                    : SEED,
    "n_total"                 : int(len(warm_start_X)),
    "n_real"                  : int(len(real_sample)),
    "n_supplement"            : int(len(supplement)),
    "premium_mean"            : float(warm_start_y.mean()),
    "premium_min"             : float(warm_start_y.min()),
    "premium_max"             : float(warm_start_y.max()),
}
meta_path.write_text(json.dumps(metadata, indent=2))

print(f"Saved → {X_path}  ({X_path.stat().st_size / 1e6:.1f} MB)")
print(f"Saved → {y_path}  ({y_path.stat().st_size / 1e6:.1f} MB)")
print(f"Saved → {meta_path}")
